### ISSUE TITLE
single robot cannot complete exploration on most maps

### ISSUE THREAD

**Issue by zj5559** [efc-robot/Explore-Bench#12]
Hi, thanks for this cool exploration benchmark!

When I try to run exploration of single robot on each map, I found that for most maps (like corner, room, corridor), the robot can only explore 1/4 or even stuck at the very beginning, and then stay still. I only run the "loop" map successfully, which seems the easiest map compared to the other maps. However, the time cost for 90% exploration is much higher than the paper mentioned. I got 393.3s for "cost" method, while the time in the paper is 124s. 

Is this because of the different hardware system? I noticed that the time counting is based on the absolute time cost, instead of the number of exploration steps of the method.

I would be appreciated if you can help me solve these two problems. (i.e., failed exploration on most maps & large gap of time cost)

**Comment by Debellert1** [comment]
Not only the single robot, but also the one using DRL cannot complete the exploration, which is very strange.？？

**Comment by FarawaySail** [comment]
This problem is most likely caused by a mismatch between your setting of the lidar range and that in our paper. 
We try to solve it in #8 .
Specifically, you should `roscd turtlebot3_description`, and check the range of base_scan in `turtlebot3_burger.gazebo.xacro`. The range should be 7m.

**Comment by Debellert1** [comment]
Thanks! I will try it today
