### ISSUE TITLE
Confusing Collaboration Metric

### ISSUE THREAD

**Issue by derektan95** [efc-robot/Explore-Bench#13]
Hi @FarawaySail, 

Thanks for your repository. I am confused by how you defined the overlap ratio. Why is the overlap area [summation(all robots' area) - total map area ] / total map area?

Let's say robot 1 explores 60pixels, robot 2 explores 40 pixels, total map has 100 pixels to be explored. By this formula, overlap ratio is [(60+40) - 100] / 100 = 0. However, there may be significant overlap between robot 1's 60px and robot 2's 40px. Do you mind explaining more on this?

<img width="518" alt="image" src="https://github.com/efc-robot/Explore-Bench/assets/48535336/311e5f1d-568a-44a6-a0e5-17a1eaa24dbe">

**Comment by FarawaySail** [comment]
`S_i`s in the formula are collected after the exploration is completed. 
In the example you provided, exploration is not over, that is, the 100 pixels are all explored.
If you want real-time overlap ratio during the exploration process, `S_total` should be the total number of pixels that have been explored so far.
