### ISSUE TITLE
merge map failed

### ISSUE THREAD

**Issue by Sorrowa** [efc-robot/Explore-Bench#15]
Thank you very much for the outstanding work of your team. 

I encountered a problem while running: 

roslaunch sim_env corridor_far_env_two_robots.launch 
roslaunch sim_env two_robots.launch 
roslaunch exploration_benchmark two_cost_node.launch 
(during the exploration process, map fusion did not occur due to unknown relative poses between robots): 

"Could not get initial position for robot." 

I think maybe the "known_init_poses" parameter in the "map_merge" node should be set to false. 

However, even after setting it, I still encountered a situation as shown in the figure below. 

![Uploading screen shot.png…]()

It seems that there is an error in map fusion. After that, I increased the "estimation_confidence" to 30.0, but the same problem still occurred.

Are there any additional modifications needed for map merge?

**Comment by Sorrowa** [comment]
Sorry, it seems that this figure is not very willing to show itself.（）
![Uploading 1713362081186.png…]()

**Comment by Sorrowa** [comment]
Sorry, it seems that this figure is not very willing to show itself.（）

**Comment by Sorrowa** [comment]
![Uploading screen shot.png…]()

**Comment by Sorrowa** [comment]
How to enable map merging? (I encountered the same issue in your team's another work https://github.com/efc-robot/SMMR-Explore)

**Comment by FarawaySail** [comment]
In this work (Explore-Bench), we assume that the multiple robots know each other's initial position.
We have `exploration_benchmark/scripts/publish_tf_for_two_robots.py` for it.
If the map is not merged, you should check the tf tree, like `rosrun rqt_tf_tree rqt_tf_tree`.
In the correct tf tree, the `robot1/map`, `robot2/map`, `robot1/odom`, and `robot2/odom` should be connected.

**Comment by Sorrowa** [comment]
Thanks very much for your help.
My question comes from: autolab_core not installed correctly.
