### ISSUE TITLE
something wrong in the function "self._resize_convert" in grid_runner.py

### ISSUE THREAD

**Issue by rickczhao** [efc-robot/Explore-Bench#17]
hello, what a great work you've done!
But i found something wrong in onpolicy/onpolicy/runner/shared/grid_runner.py.
![Screenshot from 2024-07-09 16-02-49](https://github.com/efc-robot/Explore-Bench/assets/115967014/4b862909-662c-4952-b07f-8a75a2d8f1e1)
in line 524 and 526, variables "obs" and "shared_obs" are actually the same, which are output by function "self._resize_convert" with the same input parameters.However, they are respectively used as the input of the actor and the critic.(maybe the input of the critic should be the global observation?)
Additionally, I find that "obs" and "shared_obs" are not updated in the function "self._resize_convert", in which only raw_ob is updated.

**Comment by FarawaySail** [comment]
https://github.com/marlbenchmark/on-policy/issues/104
This may be helpful for your problem. We mainly refer to the original implementation.
