### ISSUE TITLE
this launch file "two_cost_node.launch" should run in what environment,python2.7 or python 3.7

### ISSUE THREAD

**Issue by SiyiLoo** [efc-robot/Explore-Bench#2]
Running this file in either Python 2.7 or Python 3.7 will result in errors，So I want to figure out what environment to run this file in.

**Comment by FarawaySail** [comment]
Except for the scripts related to RL, scripts all run in python2.7.
If there are errors under python2.7, you can describe the errors in detail or post a screenshot.

**Comment by SiyiLoo** [comment]
The detail of this error is "ImportError: No module named autolab_core".But when I install autolab_core,there are some Syntax error.Because this package uses a lot of syntax in python3.7.Thank you so much!

**Comment by FarawaySail** [comment]
This error results from the wrong version of ```autolab_core```.
Try this: ```pip install autolab_core==0.0.14```.

**Comment by SiyiLoo** [comment]
Thank you so much,the above problem has been solved!
