### ISSUE TITLE
When I follow the tutorial to perform multi-robot exploration,exploration can not complete

### ISSUE THREAD

**Issue by SiyiLoo** [efc-robot/Explore-Bench#3]
The launch files I executed were "room_close_env_two_robots.launch","two_robots.launch","two_mmpf_node.launch".The result is shown in figure.
![2022-07-18 17-20-19 的屏幕截图](https://user-images.githubusercontent.com/61130444/180361972-041cf498-ef52-4f90-81cd-8b55d268da6a.png)

**Comment by FarawaySail** [comment]
I didn't have the problem you described when I was running the scripts.
From the screenshots, there may be something wrong with your mapping module or TF tree (I think TF is more likely to be the cause of the error). 
I suggest that you use rviz to visualize your TF tree and `rosrun rqt_tf_tree rqt_tf_tree` to check whether TF tree is correct.
