### ISSUE TITLE
How do you measure the coverage of the explored space ?

### ISSUE THREAD

**Issue by han-kyung-min** [efc-robot/Explore-Bench#4]
Dear authors,

Thanks for the nice SW. 

Your ICRA 2022 paper talks about the two coverage metrics: 1) T_total and 2) T_topo, which are associated with the coverage of the exploration space. Could you let me know how did you measure the coverage? I am working on your SW, but it seems that the SW only publishes the exploration time and the trajectory length. I cannot locate which topic outputs the coverage of the environment.

Best,

**Comment by han-kyung-min** [comment]
Nevermind. I found "exploration_metric_for_single_robot.py" script.

**Comment by han-kyung-min** [comment]
It seems that "exploration_metric_for_single_robot.py" counts the number of covered pixels in the currently built map by Cartographer. Then, it compares the map against the prebuilt map files saved in "blueprint" folder in terms of the number of known cells. However, this slam method often builds an inaccurate map (distorted), causing incorrect counts of the number of covered cells. This may lead to the wrong measures of T_90 and T_99 because the distorted map could become larger than the ground truth map. 

In order to resolve this problem, I was trying to use Octomap instead of Cartographer. However, the system randomly fails at  dismapConstruction_start_target() function. Could you please help me with this issue ?

Best

**Comment by FarawaySail** [comment]
Based on your description, I can't figure out where the problem occurred, i.e., which line in the "dismapConstruction_start_target()" function crashed. 
I can give your some useful information and possible solutions. The "dismapConstruction_start_target()" function is responsible for calculating wave-front distance in potential field, given the occupancy grid map and robot's current location. If you replace Cartographer with OctoMap, you should also use the occupancy grid map generated from OctoMap as the input of the function.

**Comment by han-kyung-min** [comment]
Thanks for the prompt reply.

I use a 2D occupancy grid map published out from Octomap (w/ 12m sensor range)

The error occurs at the code below. 
It fails to test the if-statement. Perhaps, trying to access outside of memory or something.
Any idea ?

>
           if (dismap_[(curr_iter[i][0] - 1) * WIDTH + curr_iter[i][1]] == 0)
            {
                dismap_[(curr_iter[i][0] - 1) * WIDTH + curr_iter[i][1]] = iter;
                next_iter.push_back(new int[2]{curr_iter[i][0] - 1, curr_iter[i][1]});
            }
>

The error frequently occurs in the "corner environment." when the robot arrives at the first target point.

Best,

**Comment by FarawaySail** [comment]
This problem is caused by array access out of bounds.
As written in the code, each cycle extends 4 points outward from the current point. If it is extended to the edge of the map, the array may be out of bounds. To avoid this situation, additional constraints should be added to prevent indexing points outside the map. The reason why this error did not occur in our previous implementation is that the map generated by cartographer naturally has a circle of unknown areas on the periphery (shown in the attached figure), so it will not extend to the edge. However, I think that the map generated by OctoMap does not have this characteristic, i.e., there may be free points on the edge of the map, so this error occurs. Therefore, I suggest that you add some constraints to prevent indexing points outside the map generated by OctoMap.
![test](https://user-images.githubusercontent.com/28787910/190409471-0a61030b-9c97-47e5-861c-c4f2db13f8e9.jpg)

**Comment by han-kyung-min** [comment]
I solved this problem based on your advice. Thanks for the help. I added extra padding to the border of the grid map generated by OctoMap. 

However, before I close this issue, I would like to ask a question. In my experience, Cartographer often creates inaccurate maps (distorted), estimating unstable robot position and maps. The problem gets worse if the range of the laser sensor decreases. Subsequently, the robot could make unnecessary motion plans to cover the already covered area b/c the grid map keeps changing. How did you solve this problem?

**Comment by han-kyung-min** [comment]
Thanks  for  the reply, but I  am not  sure  if I  understand your  answer.

Did  you  mean that the  map  created  by  cartographer have extra padding
at the border  of the  original map (with UNKNOWN labels) while Octomap
doesn't?


Best


2022년 9월 15일 (목) 오후 9:59, Yuanfan Xu ***@***.***>님이 작성:

**Comment by FarawaySail** [comment]
> Thanks for the reply, but I am not sure if I understand your answer. Did you mean that the map created by cartographer have extra padding at the border of the original map (with UNKNOWN labels) while Octomap doesn't? Best 2022년 9월 15일 (목) 오후 9:59, Yuanfan Xu ***@***.***>님이 작성:

Yes, you're right.
