### ISSUE TITLE
There's something wrong in your readme.

### ISSUE THREAD

**Issue by jimazeyu** [efc-robot/Explore-Bench#6]
Your code in the readme is:
echo 'export TURTLEBOT3_MODEL=burger' > ~/.bashrc
This would rewrite the whole file. It should be:
echo 'export TURTLEBOT3_MODEL=burger' >> ~/.bashrc

**Comment by citaer** [comment]
I'm regret not seeing your issue. When my ~/.bashrc is empty but "export TURTLEBOT3_MODEL=burger", I want to push an issue and seeing yours.

**Comment by FarawaySail** [comment]
Thank you for catching this error, and I update the readme.
