### ISSUE TITLE
Exploration Issue

### ISSUE THREAD

**Issue by derektan95** [efc-robot/Explore-Bench#8]
Hi @FarawaySail, 

Thank you for this exploration benchmark. It's a really cool and important initiative, which will help us with benchmarking our exploration code. 

Unfortunately, the baselines you have provided does not seem to work. On all the examples of the launch files you have given, they all seem to be stuck and are unable to progress with exploration.

Do you have any insights as to why? 

Thanks again, 
Derek Tan

**Comment by FarawaySail** [comment]
Hi Derek,

From the video you provided, I guess the possible reason is that the range of the LiDAR has not been modified. We used 7m in our paper, while the default turtlebot burger is 3.5m. I don't know if this is the reason why the exploration is stuck.

**Comment by derektan95** [comment]
Hi @FarawaySail, 

Let me give this a shot. Thanks for your help!
