### ISSUE TITLE
Issue about Exploration on a large map

### ISSUE THREAD

**Issue by Yixiao-M** [efc-robot/Explore-Bench#9]
Hi, @FarawaySail 
Your "Explore Bench" tool is fantastic! It's been incredibly helpful in our research. Thank you for creating such a wonderful resource.

Unfortunately, when testing exploration on a large map, such as the "tunnel" map in the CMU environment, I have encountered issues. If I run multiple robot explorations, the planner script (MMPF, RRT, etc.) crashes at the beginning.

Here is the video link: https://drive.google.com/file/d/1SOM2cDIWOeORzpQJ1U9p4Q5evb3Ozrxl/view?usp=drive_link
error msg: https://drive.google.com/file/d/1CL56A7B5Q_g1buQdUBNWa4UtXBc2pjl5/view?usp=drive_link

But when running a single robot exploration, the planner script crashes when the explored map is too large.

Here is the video link: https://drive.google.com/file/d/1PN73ti6xHTDqwFe5T1olAV_QZZe04yWh/view?usp=drive_link
error msg: https://drive.google.com/file/d/1CvzsvO_zpnM93zzvge4-2FxsK7e4iD9s/view?usp=drive_link

Although it said the error log is in the "robot1_mmpf-1.log", this file does not exist.

Do you have any insights on this?

**Comment by FarawaySail** [comment]
Thank you for using our code repository.
The reason for this problem, I think, is that there is not enough device memory left. In the MMPF implementation, we construct dismap for each frontier obtained by clustering (line 496-506 in mmpf_node.cpp). When the map is large, the number of frontiers, the height and the width are all large, resulting in the need to new a very large amount of memory. It may be that an error was reported during the process. 
There are two ways to solve this problem: one is to reduce the number of clustering centers, i.e., to increase the range of clusters (line 450 in mmpf_node.cpp); the other is to add restrictions by not considering clustering centers that are particularly far away, etc.
The above is my guess. The strange thing is that if my guess is right, rrt and cost methods should not have this problem.

**Comment by Yixiao-M** [comment]
> Thank you for using our code repository. The reason for this problem, I think, is that there is not enough device memory left. In the MMPF implementation, we construct dismap for each frontier obtained by clustering (line 496-506 in mmpf_node.cpp). When the map is large, the number of frontiers, the height and the width are all large, resulting in the need to new a very large amount of memory. It may be that an error was reported during the process. There are two ways to solve this problem: one is to reduce the number of clustering centers, i.e., to increase the range of clusters (line 450 in mmpf_node.cpp); the other is to add restrictions by not considering clustering centers that are particularly far away, etc. The above is my guess. The strange thing is that if my guess is right, rrt and cost methods should not have this problem.

It's great to hear back from you with such a detailed response! Thank you so much for taking the time to provide such valuable information. Your assumption is accurate - the crash is caused by a memory issue. In "mmpf_node.cpp" line 269, a large array is declared with "int map[HEIGHT*WIDTH];".  However, the following code did not free it, resulting in a crash. The issue can be resolved by replacing it with "std::vector<int> map(HEIGHT*WIDTH)".

After resolving the issue, we encountered another obstacle. It seems that robots have difficulty exploring large maps and get stuck frequently. Do you have any insights about it?

**Comment by FarawaySail** [comment]
From your description, I'm not quite sure which program is causing the bot to get stuck.

If it is `move_base` that is stuck, my suggestion would be to fine tune the parameters in the move_base package; if it is the explorer that is stuck, my guess is that the big map results in the large amount of computation and the robot needs to wait for the target point to be calculated before it will continue to move.
